#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerCollection.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="beercollection")]
	public partial class DbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBeer(Beer instance);
    partial void UpdateBeer(Beer instance);
    partial void DeleteBeer(Beer instance);
    #endregion
		
		public DbDataContext() : 
				base("Data Source=(local);Initial Catalog=beercollection;Integrated Security=True", mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Beer> Beers
		{
			get
			{
				return this.GetTable<Beer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Beer")]
	public partial class Beer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BeerId;
		
		private string _Name;
		
		private string _Description;
		
		private string _Picture;
		
		private System.Nullable<decimal> _AlcoholPercentageByVolume;
		
		private System.DateTime _DrinkBy;
		
		private bool _IsConsumed;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBeerIdChanging(int value);
    partial void OnBeerIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPictureChanging(string value);
    partial void OnPictureChanged();
    partial void OnAlcoholPercentageByVolumeChanging(System.Nullable<decimal> value);
    partial void OnAlcoholPercentageByVolumeChanged();
    partial void OnDrinkByChanging(System.DateTime value);
    partial void OnDrinkByChanged();
    partial void OnIsConsumedChanging(bool value);
    partial void OnIsConsumedChanged();
    #endregion
		
		public Beer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeerId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BeerId
		{
			get
			{
				return this._BeerId;
			}
			set
			{
				if ((this._BeerId != value))
				{
					this.OnBeerIdChanging(value);
					this.SendPropertyChanging();
					this._BeerId = value;
					this.SendPropertyChanged("BeerId");
					this.OnBeerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(4000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="NVarChar(4000)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlcoholPercentageByVolume", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> AlcoholPercentageByVolume
		{
			get
			{
				return this._AlcoholPercentageByVolume;
			}
			set
			{
				if ((this._AlcoholPercentageByVolume != value))
				{
					this.OnAlcoholPercentageByVolumeChanging(value);
					this.SendPropertyChanging();
					this._AlcoholPercentageByVolume = value;
					this.SendPropertyChanged("AlcoholPercentageByVolume");
					this.OnAlcoholPercentageByVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrinkBy", DbType="DateTime NOT NULL")]
		public System.DateTime DrinkBy
		{
			get
			{
				return this._DrinkBy;
			}
			set
			{
				if ((this._DrinkBy != value))
				{
					this.OnDrinkByChanging(value);
					this.SendPropertyChanging();
					this._DrinkBy = value;
					this.SendPropertyChanged("DrinkBy");
					this.OnDrinkByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsConsumed", DbType="Bit NOT NULL")]
		public bool IsConsumed
		{
			get
			{
				return this._IsConsumed;
			}
			set
			{
				if ((this._IsConsumed != value))
				{
					this.OnIsConsumedChanging(value);
					this.SendPropertyChanging();
					this._IsConsumed = value;
					this.SendPropertyChanged("IsConsumed");
					this.OnIsConsumedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
